command:
  - "bash"
  - "-c"
  - "pip install --no-cache-dir -e . && python databricks_app.py"
resources:
  - name: "sql-warehouse"
    sql_warehouse: {}
env:
  - name: "OPENCITE_ENABLE_OTEL"
    value: "true"
  - name: "OPENCITE_ENABLE_DATABRICKS"
    value: "true"
  - name: "OPENCITE_PERSISTENCE_ENABLED"
    value: "true"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "OPENCITE_DATABRICKS_CATALOG"
    value: "ai-data"
  - name: "OPENCITE_DATABRICKS_SCHEMA"
    value: "default"
  - name: "OPENCITE_AI_GATEWAY_USAGE_TABLE"
    value: "workspace.default.gateway_usage"
